from django.apps import AppConfig


class IdentitysystemConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'IdentitySystem'

    def ready(self):
        from .models import Region, Department
        if Region.objects.count() == 0:
            Region.objects.create(
                name='CENTRE'
            )
            Region.objects.create(
                name='SUD'
            )
            Region.objects.create(
                name='LITTORAL'
            )
            Region.objects.create(
                name='EST'
            )
            Region.objects.create(
                name='OUEST'
            )
            Region.objects.create(
                name='NORD'
            )
            Region.objects.create(
                name='EXTREME-NORD'
            )
            Region.objects.create(
                name='ADAMAOUA'
            )
            Region.objects.create(
                name='NORD-OUEST'
            )
            Region.objects.create(
                name='SUD-OUEST'
            )
        if Department.objects.count() == 0:
            Department.objects.create(
                name='Haute-Sanaga',
                fk_region_id=1
            )
            Department.objects.create(
                name='Lekié',
                fk_region_id = 1
            )
            Department.objects.create(
                name='Mbam-et-Inoubou',
                fk_region_id = 1
            )
            Department.objects.create(
                name='Mbam-et-Kim',
                fk_region_id = 1
            )
            Department.objects.create(
                name='Méfou-et-Afamba',
                fk_region_id=1
            )
            Department.objects.create(
                name='Méfou-et-Akono',
                fk_region_id=1
            )
            Department.objects.create(
                name='Mfoundi',
                fk_region_id=1
            )
            Department.objects.create(
                name='Nyong-et-Kéllé',
                fk_region_id=1
            )
            Department.objects.create(
                name='Nyong-et-Mfoumou',
                fk_region_id=1
            )
            Department.objects.create(
                name='Nyong-et-Soo',
                fk_region_id=1
            )
            Department.objects.create(
                name='Dja-et-Lobo',
                fk_region_id=2
            )
            Department.objects.create(
                name='Mvila',
                fk_region_id=2
            )
            Department.objects.create(
                name='Océan',
                fk_region_id=2
            )
            Department.objects.create(
                name='Vallée-du-Ntem',
                fk_region_id=2
            )
            Department.objects.create(
                name='Moungo',
                fk_region_id=3
            )
            Department.objects.create(
                name='Nkam',
                fk_region_id=3
            )
            Department.objects.create(
                name='Sanaga-Maritime',
                fk_region_id=3
            )
            Department.objects.create(
                name='Wouri',
                fk_region_id=3
            )
            Department.objects.create(
                name='Boumba-et-Ngoko',
                fk_region_id=4
            )
            Department.objects.create(
                name='Haut-Nyong',
                fk_region_id=4
            )
            Department.objects.create(
                name='Kadey',
                fk_region_id=4
            )
            Department.objects.create(
                name='Lom-et-Djerem',
                fk_region_id=4
            )
            Department.objects.create(
                name='Bamboutos',
                fk_region_id=5
            )
            Department.objects.create(
                name='Haut-Nkam',
                fk_region_id=5
            )
            Department.objects.create(
                name='Hauts-Plateaux',
                fk_region_id=5
            )
            Department.objects.create(
                name='Koung-Khi',
                fk_region_id=5
            )
            Department.objects.create(
                name='Menoua',
                fk_region_id=5
            )
            Department.objects.create(
                name='Mifi',
                fk_region_id=5
            )
            Department.objects.create(
                name='Ndé',
                fk_region_id=5
            )
            Department.objects.create(
                name='Noun',
                fk_region_id=5
            )
            Department.objects.create(
                name='Bénoué',
                fk_region_id=6
            )
            Department.objects.create(
                name='Faro',
                fk_region_id=6
            )
            Department.objects.create(
                name='Mayo-Louti',
                fk_region_id=6
            )
            Department.objects.create(
                name='Mayo-Rey',
                fk_region_id=6
            )
            Department.objects.create(
                name='Diamaré',
                fk_region_id=7
            )
            Department.objects.create(
                name='Logone-et-Chari',
                fk_region_id=7
            )
            Department.objects.create(
                name='Mayo-Danay',
                fk_region_id=7
            )
            Department.objects.create(
                name='Mayo-Kani',
                fk_region_id=7
            )
            Department.objects.create(
                name='Mayo-Sava',
                fk_region_id=7
            )
            Department.objects.create(
                name='Mayo-Tsanaga',
                fk_region_id=7
            )
            Department.objects.create(
                name='Djérem',
                fk_region_id=8
            )
            Department.objects.create(
                name='Faro-et-Déo',
                fk_region_id=8
            )
            Department.objects.create(
                name='Mayo-Banyo',
                fk_region_id=8
            )
            Department.objects.create(
                name='Mbéré',
                fk_region_id=8
            )
            Department.objects.create(
                name='Vina',
                fk_region_id=8
            )
            Department.objects.create(
                name='Boyo',
                fk_region_id=9
            )
            Department.objects.create(
                name='Bui',
                fk_region_id=9
            )
            Department.objects.create(
                name='Donga-Mantung',
                fk_region_id=9
            )
            Department.objects.create(
                name='Menchum',
                fk_region_id=9
            )
            Department.objects.create(
                name='Mezam',
                fk_region_id=9
            )
            Department.objects.create(
                name='Momo',
                fk_region_id=9
            )
            Department.objects.create(
                name='Ngo-KetunJia',
                fk_region_id=9
            )
            Department.objects.create(
                name='Fako',
                fk_region_id=10
            )
            Department.objects.create(
                name='Koupé-Manengouba',
                fk_region_id=10
            )
            Department.objects.create(
                name='Lebialem',
                fk_region_id=10
            )
            Department.objects.create(
                name='Manyu',
                fk_region_id=10
            )
            Department.objects.create(
                name='Meme',
                fk_region_id=10
            )
            Department.objects.create(
                name='Ndian',
                fk_region_id=10
            )


