# Generated by Django 4.1.7 on 2023-04-25 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Borough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IdentityCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_number', models.CharField(max_length=100)),
                ('deliverance_date', models.DateField()),
                ('expired_date', models.DateField()),
                ('fk_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authority', to='IdentitySystem.authority')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.IntegerField(choices=[(0, 'Female'), (1, 'Male')])),
                ('Height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('photo', models.ImageField(upload_to='')),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('fk_identity_card', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='IdentitySystem.identitycard')),
                ('place_of_birth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IdentitySystem.borough')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fk_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region', to='IdentitySystem.region')),
            ],
        ),
        migrations.AddField(
            model_name='borough',
            name='fk_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='IdentitySystem.department'),
        ),
    ]
