# Generated by Django 4.1.7 on 2023-06-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdentitySystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedposter',
            name='photos',
            field=models.BinaryField(null=True),
        ),
    ]
