# Generated by Django 4.1.7 on 2023-04-26 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IdentitySystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='fk_identity_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IdentitySystem.identitycard'),
        ),
    ]
