# Generated by Django 4.1.7 on 2023-06-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdentitySystem', '0002_alter_wantedposter_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedposter',
            name='photos',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
