# Generated by Django 4.1.7 on 2023-06-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdentitySystem', '0003_alter_wantedposter_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedposter',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
